package com.jiawa.train.gateway.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.core.env.Environment;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@ComponentScan("com.jiawa")
public class GatewayApplication {

    private static final Logger L0G = LoggerFactory.getLogger(GatewayApplication.class);
    public static void main(String[] args) {
//        ConfigurableApplicationContext run = SpringApplication.run(GatewayApplication.class, args);
//
//        // 添加启动日志
//        ConfigurableEnvironment environment = run.getEnvironment();
//        L0G.info("启动成功！！！！");
//        L0G.info("地址：\thttp://127.0.0.1:{}", environment.getProperty("server.port"));

        SpringApplication app = new SpringApplication(GatewayApplication.class);
        Environment env = app.run(args).getEnvironment();
        L0G.info("启动成功！！");
        L0G.info("测试地址：\thttp://127.0.0.1:{}/hello", env.getProperty("server.port"));

    }

}
